### ISSUE TITLE
Outlier treatment

### ISSUE THREAD

**Issue by asarfraaz** [Shanmugapriya03/Parkinson-s-Disease#1]
I was intrigued by the outlier treatment for Parkinson's Disease dataset that is performed in the EDA notebook here. I see that some features have been treated with the mean [ of the non-outlier values ] whereas some have been treated by their max. Can you let me know the criteria to decide which mask value to choose for each feature ?

**Comment by Shanmugapriya03** [comment]
@asarfraaz  Thanks for checking out my Repo. When I was working on this dataset I was a newbie and was simply playing with the dataset. There is no specific reason for the mask value I have chosen.
